# Generated by Django 3.2.4 on 2021-06-21 08:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hoso',
            fields=[
                ('sodangky', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Số đăng ký')),
                ('ngaycap', models.DateField(verbose_name='Ngày cấp')),
                ('ngayhethan', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn')),
                ('sotucongbo', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Số tự công bố')),
                ('tensanpham', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('hansanpham', models.IntegerField(null=True, verbose_name='Hạn sử dụng')),
                ('hoatchat', models.TextField(blank=True, null=True, verbose_name='Hoạt chất')),
                ('hamluong', models.TextField(blank=True, null=True, verbose_name='Hàm lượng')),
                ('dangbaoche', models.TextField(blank=True, null=True, verbose_name='Dạng bào chế')),
                ('tieuchuan', models.CharField(blank=True, max_length=64, null=True, verbose_name='Tiêu chuẩn')),
                ('nhadk', models.CharField(blank=True, max_length=64, null=True, verbose_name='Nhà đăng ký')),
                ('nhapp', models.CharField(blank=True, max_length=64, null=True, verbose_name='Nhà phân phối')),
                ('quycach', models.TextField(blank=True, null=True, verbose_name='Quy cách')),
                ('phanloai', models.CharField(choices=[('Thuốc', 'Thuốc'), ('Thực phẩm chức năng', 'Thực phẩm chức năng'), ('Mỹ phẩm', 'Mỹ phẩm'), ('Trang thiết bị', 'Trang thiết bị'), ('Sinh phẩm', 'Sinh phẩm')], max_length=64, verbose_name='Phân loại')),
            ],
        ),
        migrations.CreateModel(
            name='marquette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marquette', models.CharField(max_length=64, verbose_name='Mã marquette')),
            ],
        ),
        migrations.CreateModel(
            name='marquettedat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonkho', models.IntegerField(verbose_name='Tồn kho thực tế')),
                ('dathang', models.IntegerField(verbose_name='Số lượng đặt')),
                ('marquettedat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madat', to='marquette.marquette', verbose_name='Mã hàng đã đặt')),
            ],
        ),
        migrations.CreateModel(
            name='nhacungcap',
            fields=[
                ('ten', models.CharField(max_length=255, verbose_name='Nhà cung cấp')),
                ('ma', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Mã nhà cung cấp')),
            ],
        ),
        migrations.CreateModel(
            name='phulieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mabfomoi', models.CharField(max_length=6, verbose_name='Mã BFO phụ liệu mới')),
                ('mabfocu', models.CharField(max_length=6, null=True, verbose_name='Mã BFO phụ liệu cũ')),
                ('loai', models.CharField(choices=[('Cầu', 'Cầu'), ('Hộp nhỏ', 'Hộp nhỏ'), ('Hộp trung gian', 'Hộp trung gian'), ('Khay cài', 'Khay cài'), ('Màng co', 'Màng co'), ('Màng nhôm', 'Màng nhôm'), ('Màng viên đặt', 'Màng viên đặt'), ('Tem chính', 'Tem chính'), ('Tem phụ', 'Tem phụ'), ('Toa', 'Toa'), ('Tuýp', 'Tuýp'), ('Túi', 'Túi')], max_length=64, verbose_name='Loại')),
                ('lanbanhanh', models.IntegerField(verbose_name='Lần ban hành')),
                ('dauma', models.CharField(max_length=6, verbose_name='Đầu mã')),
                ('trangthaihoso', models.CharField(choices=[('Bản in', 'Bản in'), ('Hoàn thành', 'Hoàn thành')], max_length=64, null=True, verbose_name='Trạng thái')),
                ('soluong', models.IntegerField(null=True, verbose_name='Số lượng')),
            ],
            options={
                'unique_together': {('mabfomoi', 'dauma')},
            },
        ),
        migrations.CreateModel(
            name='sanpham',
            fields=[
                ('mabfo', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Mã BFO sản phẩm')),
                ('quycach', models.TextField(verbose_name='Quy cách')),
                ('vitri', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Vị trí nhập theo dạng 1-1-1', regex='[0-9]-[0-9]-[0-10]')], verbose_name='Vị trí')),
            ],
        ),
        migrations.CreateModel(
            name='thaydoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plsau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plsau', to='marquette.phulieu', verbose_name='Phụ liệu sau')),
                ('pltruoc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pltruoc', to='marquette.phulieu', verbose_name='Phụ liệu trước')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spthaydoi', to='marquette.sanpham', verbose_name='Sản phẩm')),
            ],
        ),
        migrations.CreateModel(
            name='xuly',
            fields=[
                ('thaydoi', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='xulythaydoi', serialize=False, to='marquette.thaydoi', verbose_name='Thay đổi')),
                ('xuly', models.TextField(verbose_name='Hướng xử lý')),
                ('chotxuly', models.CharField(choices=[('Đã chốt', 'Đã chốt'), ('Chưa chốt', 'Chưa chốt')], max_length=64, verbose_name='Tình trạng chốt')),
                ('thoihan', models.DateField(null=True, verbose_name='Thời hạn thực hiện')),
                ('lenhsx', models.CharField(max_length=255, null=True, verbose_name='Lệnh sản xuất')),
                ('ngaysx', models.DateField(null=True, verbose_name='Ngày sản xuất')),
                ('hansd', models.DateField(null=True, verbose_name='Hạn sử dụng')),
                ('khsx', models.CharField(max_length=255, null=True, verbose_name='Kế hoạch sản xuất')),
                ('trangthai', models.CharField(choices=[('Hoàn thành', 'Hoàn thành'), ('Chưa hoàn thành', 'Chưa hoàn thành')], max_length=64, verbose_name='Trạng thái')),
                ('ngaychot', models.DateField(blank=True, null=True, verbose_name='Ngày chốt')),
                ('chothuy', models.CharField(choices=[('H', 'Hủy'), ('K', 'Không hủy')], max_length=64, null=True, verbose_name='Chốt hủy')),
            ],
        ),
        migrations.CreateModel(
            name='thongbao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congvan', models.CharField(max_length=20, null=True, verbose_name='Số công văn thay đổi')),
                ('ngayhethancv', models.DateField(verbose_name='Ngày hết hạn hiệu lực công văn')),
                ('ngayapdung', models.DateField(verbose_name='Ngày áp dụng thay đổi')),
                ('loai', models.CharField(choices=[('BB', 'Bắt buộc'), ('THT', 'Tự hoàn thiện')], max_length=6, verbose_name='Loại thay đổi')),
                ('uutien', models.CharField(choices=[('G', 'Gấp'), ('T', 'Thông thường')], max_length=6, verbose_name='Mức độ ưu tiên')),
                ('lydo', models.CharField(choices=[('CPC1', 'Công ty cổ phần dược phẩm CPC1 Hà Nội'), ('NPP', 'Nhà phân phối')], max_length=6, verbose_name='Lý do thay đổi')),
                ('mahangdat', models.ManyToManyField(through='marquette.marquettedat', to='marquette.marquette', verbose_name='Mã hàng đã đặt')),
                ('sodangky', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sdkthaydoi', to='marquette.hoso', verbose_name='Số đăng ký')),
            ],
        ),
        migrations.AddField(
            model_name='thaydoi',
            name='thongbao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thaydoi', to='marquette.thongbao', verbose_name='Thay đổi'),
        ),
        migrations.CreateModel(
            name='sudung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.BooleanField(verbose_name='Hiệu lực sử dụng')),
                ('pl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plusing', to='marquette.phulieu', verbose_name='Phụ liệu')),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spusing', to='marquette.sanpham', verbose_name='Sản phẩm')),
            ],
        ),
        migrations.CreateModel(
            name='sosanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noidung', models.TextField(verbose_name='Nội dung so sánh')),
                ('chutruoc', models.TextField(null=True, verbose_name='Nội dung trước')),
                ('chusau', models.TextField(null=True, verbose_name='Nội dung hiện tại')),
                ('anhtruoc', models.ImageField(null=True, upload_to='', verbose_name='Hình ảnh trước')),
                ('anhsau', models.ImageField(null=True, upload_to='', verbose_name='Hình ảnh hiện tại')),
                ('masau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marquettesau', to='marquette.marquette', verbose_name='Marquette sau')),
                ('matruoc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marquettetruoc', to='marquette.marquette', verbose_name='Marquette trước')),
                ('thongbao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thongbao', to='marquette.thongbao', verbose_name='Thông báo thay đổi')),
            ],
        ),
        migrations.AddField(
            model_name='sanpham',
            name='phulieu',
            field=models.ManyToManyField(through='marquette.sudung', to='marquette.phulieu', verbose_name='Phụ liệu'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='sodangky',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hososdk', to='marquette.hoso', verbose_name='Số đăng ký'),
        ),
        migrations.AddField(
            model_name='marquettedat',
            name='thongbao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tbao', to='marquette.thongbao', verbose_name='Thông báo thay đổi'),
        ),
        migrations.AddField(
            model_name='marquette',
            name='manhacc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nhacc', to='marquette.nhacungcap', verbose_name='Nhà cung cấp'),
        ),
        migrations.AddField(
            model_name='marquette',
            name='phulieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phulieu', to='marquette.phulieu', verbose_name='Phụ liệu'),
        ),
        migrations.CreateModel(
            name='choghepmabfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quycach', models.CharField(max_length=64, verbose_name='Quy cách')),
                ('vitri', models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Vị trí nhập theo dạng 1-1-1', regex='[0-9]-[0-9]-*')], verbose_name='Vị trí')),
                ('phulieu', models.ManyToManyField(related_name='phulieucho', to='marquette.phulieu', verbose_name='Phụ liệu')),
                ('sodangky', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanphamcho', to='marquette.hoso', verbose_name='Số đăng ký')),
            ],
        ),
    ]
