# Generated by Django 3.2.4 on 2021-06-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marquette', '0003_auto_20210623_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosanh',
            name='noidung',
            field=models.TextField(null=True, verbose_name='So sánh'),
        ),
    ]
