# Generated by Django 3.2.4 on 2021-06-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marquette', '0005_alter_sosanh_thongbao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marquettedat',
            name='dathang',
            field=models.IntegerField(null=True, verbose_name='Số lượng đặt'),
        ),
        migrations.AlterField(
            model_name='marquettedat',
            name='tonkho',
            field=models.IntegerField(null=True, verbose_name='Tồn kho thực tế'),
        ),
    ]
