# Generated by Django 3.2.4 on 2021-06-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marquette', '0006_auto_20210624_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongbao',
            name='ngayhethancv',
            field=models.DateField(null=True, verbose_name='Ngày hết hạn hiệu lực công văn'),
        ),
    ]
