# Generated by Django 3.2.4 on 2021-07-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marquette', '0008_auto_20210628_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='vitri',
            field=models.CharField(max_length=6, null=True, verbose_name='Vị trí'),
        ),
        migrations.AlterField(
            model_name='sosanh',
            name='anhsau',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Hình ảnh hiện tại'),
        ),
        migrations.AlterField(
            model_name='sosanh',
            name='anhtruoc',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Hình ảnh trước'),
        ),
    ]
