# Generated by Django 3.2.4 on 2021-07-02 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marquette', '0009_auto_20210702_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sosanh',
            name='anhsau',
        ),
        migrations.RemoveField(
            model_name='sosanh',
            name='anhtruoc',
        ),
        migrations.RemoveField(
            model_name='sosanh',
            name='chusau',
        ),
        migrations.RemoveField(
            model_name='sosanh',
            name='chutruoc',
        ),
        migrations.AlterField(
            model_name='phulieu',
            name='mabfomoi',
            field=models.CharField(max_length=6, verbose_name='Mã BFO phụ liệu (Fast)'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='vitri',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Vị trí'),
        ),
        migrations.AlterField(
            model_name='sosanh',
            name='noidung',
            field=models.TextField(null=True, verbose_name='Nội dung so sánh'),
        ),
        migrations.AlterUniqueTogether(
            name='phulieu',
            unique_together={('mabfomoi', 'lanbanhanh')},
        ),
        migrations.CreateModel(
            name='sosanhtext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noidung', models.TextField(null=True, verbose_name='Nội dung so sánh')),
                ('chutruoc', models.TextField(null=True, verbose_name='Nội dung trước')),
                ('chusau', models.TextField(null=True, verbose_name='Nội dung hiện tại')),
                ('sosanh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sstext', to='marquette.sosanh')),
            ],
        ),
        migrations.CreateModel(
            name='sosanhimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noidung', models.TextField(null=True, verbose_name='Nội dung so sánh')),
                ('anhtruoc', models.ImageField(null=True, upload_to='images', verbose_name='Hình ảnh trước')),
                ('anhsau', models.ImageField(null=True, upload_to='images', verbose_name='Hình ảnh hiện tại')),
                ('sosanh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssimage', to='marquette.sosanh')),
            ],
        ),
    ]
