# Generated by Django 3.2.4 on 2021-07-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marquette', '0010_auto_20210703_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosanh',
            name='masau',
            field=models.CharField(default='', max_length=64, verbose_name='Marquette sau'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sosanh',
            name='matruoc',
            field=models.CharField(default='', max_length=64, verbose_name='Marquette trước'),
            preserve_default=False,
        ),
    ]
